import type { City } from "./demoFlow";

export type QuartierType = "residential" | "touristique" | "affaires";

export interface QuartierData {
  id: string;
  name: string;
  city: City;
  type: QuartierType;
  pricePerM2Min: number;
  pricePerM2Max: number;
  medianRent: number;
  airbnbRate: number;
  grossYield: number;
  annualAppreciation: number;
  vacancyRate: number;
  investmentScore: number;
  description: string;
}

export const QUARTIERS: Record<City, QuartierData[]> = {
  fes: [
    {
      id: "fes-medina",
      name: "Médina",
      city: "fes",
      type: "touristique",
      pricePerM2Min: 8500,
      pricePerM2Max: 12000,
      medianRent: 3500,
      airbnbRate: 65,
      grossYield: 5.2,
      annualAppreciation: 3.5,
      vacancyRate: 8,
      investmentScore: 72,
      description: "Cœur historique de Fès avec forte demande touristique",
    },
    {
      id: "fes-agdal",
      name: "Agdal",
      city: "fes",
      type: "residential",
      pricePerM2Min: 6500,
      pricePerM2Max: 9000,
      medianRent: 2800,
      airbnbRate: 35,
      grossYield: 4.8,
      annualAppreciation: 2.8,
      vacancyRate: 5,
      investmentScore: 65,
      description: "Quartier résidentiel calme avec bonne accessibilité",
    },
    {
      id: "fes-champs",
      name: "Champs de Course",
      city: "fes",
      type: "residential",
      pricePerM2Min: 5500,
      pricePerM2Max: 7500,
      medianRent: 2200,
      airbnbRate: 20,
      grossYield: 4.2,
      annualAppreciation: 2.2,
      vacancyRate: 6,
      investmentScore: 58,
      description: "Zone résidentielle en développement",
    },
    {
      id: "fes-saiss",
      name: "Saïss",
      city: "fes",
      type: "residential",
      pricePerM2Min: 7000,
      pricePerM2Max: 10000,
      medianRent: 3000,
      airbnbRate: 40,
      grossYield: 4.9,
      annualAppreciation: 3,
      vacancyRate: 7,
      investmentScore: 68,
      description: "Zone moderne avec services et commerces",
    },
    {
      id: "fes-jdid",
      name: "Fès El Jdid",
      city: "fes",
      type: "touristique",
      pricePerM2Min: 9000,
      pricePerM2Max: 13000,
      medianRent: 4000,
      airbnbRate: 70,
      grossYield: 5.5,
      annualAppreciation: 3.8,
      vacancyRate: 10,
      investmentScore: 75,
      description: "Quartier historique avec forte attractivité touristique",
    },
    {
      id: "fes-narjiss",
      name: "Narjiss",
      city: "fes",
      type: "residential",
      pricePerM2Min: 6000,
      pricePerM2Max: 8500,
      medianRent: 2500,
      airbnbRate: 25,
      grossYield: 4.5,
      annualAppreciation: 2.5,
      vacancyRate: 6,
      investmentScore: 62,
      description: "Quartier résidentiel en expansion",
    },
    {
      id: "fes-bensouda",
      name: "Ben Souda",
      city: "fes",
      type: "residential",
      pricePerM2Min: 5000,
      pricePerM2Max: 7000,
      medianRent: 2000,
      airbnbRate: 15,
      grossYield: 4,
      annualAppreciation: 2,
      vacancyRate: 8,
      investmentScore: 55,
      description: "Zone périphérique avec potentiel de croissance",
    },
  ],
  rabat: [
    {
      id: "rabat-agdal",
      name: "Agdal/Hassan",
      city: "rabat",
      type: "affaires",
      pricePerM2Min: 12000,
      pricePerM2Max: 18000,
      medianRent: 5500,
      airbnbRate: 55,
      grossYield: 5,
      annualAppreciation: 4.2,
      vacancyRate: 4,
      investmentScore: 78,
      description: "Quartier premium avec prestige et stabilité",
    },
    {
      id: "rabat-hayriad",
      name: "Hay Riad",
      city: "rabat",
      type: "residential",
      pricePerM2Min: 9000,
      pricePerM2Max: 13000,
      medianRent: 4000,
      airbnbRate: 40,
      grossYield: 4.7,
      annualAppreciation: 3.5,
      vacancyRate: 5,
      investmentScore: 72,
      description: "Quartier résidentiel moderne et sécurisé",
    },
    {
      id: "rabat-medina",
      name: "Médina",
      city: "rabat",
      type: "touristique",
      pricePerM2Min: 10000,
      pricePerM2Max: 15000,
      medianRent: 4500,
      airbnbRate: 60,
      grossYield: 5.2,
      annualAppreciation: 3.8,
      vacancyRate: 6,
      investmentScore: 75,
      description: "Cœur touristique avec charme historique",
    },
    {
      id: "rabat-souissi",
      name: "Souissi",
      city: "rabat",
      type: "affaires",
      pricePerM2Min: 11000,
      pricePerM2Max: 16000,
      medianRent: 5000,
      airbnbRate: 50,
      grossYield: 4.9,
      annualAppreciation: 4,
      vacancyRate: 4,
      investmentScore: 76,
      description: "Zone affaires avec excellente infrastructure",
    },
    {
      id: "rabat-aviation",
      name: "Aviation",
      city: "rabat",
      type: "residential",
      pricePerM2Min: 8000,
      pricePerM2Max: 11000,
      medianRent: 3500,
      airbnbRate: 35,
      grossYield: 4.5,
      annualAppreciation: 3,
      vacancyRate: 5,
      investmentScore: 68,
      description: "Quartier résidentiel accessible et dynamique",
    },
    {
      id: "rabat-yacoub",
      name: "Yacoub El Mansour",
      city: "rabat",
      type: "affaires",
      pricePerM2Min: 10500,
      pricePerM2Max: 14500,
      medianRent: 4800,
      airbnbRate: 45,
      grossYield: 4.8,
      annualAppreciation: 3.6,
      vacancyRate: 5,
      investmentScore: 73,
      description: "Zone mixte résidentielle et affaires",
    },
    {
      id: "rabat-sale",
      name: "Salé/Temara",
      city: "rabat",
      type: "residential",
      pricePerM2Min: 6500,
      pricePerM2Max: 9000,
      medianRent: 2800,
      airbnbRate: 25,
      grossYield: 4.2,
      annualAppreciation: 2.5,
      vacancyRate: 6,
      investmentScore: 62,
      description: "Zone périphérique en développement",
    },
  ],
  casa: [
    {
      id: "casa-anfa",
      name: "Anfa/Californie",
      city: "casa",
      type: "affaires",
      pricePerM2Min: 14000,
      pricePerM2Max: 20000,
      medianRent: 6500,
      airbnbRate: 60,
      grossYield: 5.3,
      annualAppreciation: 4.5,
      vacancyRate: 3,
      investmentScore: 82,
      description: "Quartier haut de gamme avec vue mer",
    },
    {
      id: "casa-maarif",
      name: "Maarif/Gauthier",
      city: "casa",
      type: "affaires",
      pricePerM2Min: 12000,
      pricePerM2Max: 17000,
      medianRent: 5500,
      airbnbRate: 55,
      grossYield: 5,
      annualAppreciation: 4,
      vacancyRate: 4,
      investmentScore: 79,
      description: "Centre affaires dynamique et cosmopolite",
    },
    {
      id: "casa-cfc",
      name: "CFC/Sidi Maârouf",
      city: "casa",
      type: "residential",
      pricePerM2Min: 8500,
      pricePerM2Max: 12000,
      medianRent: 4000,
      airbnbRate: 40,
      grossYield: 4.7,
      annualAppreciation: 3.5,
      vacancyRate: 5,
      investmentScore: 71,
      description: "Zone résidentielle moderne et sécurisée",
    },
    {
      id: "casa-hassani",
      name: "Hay Hassani",
      city: "casa",
      type: "residential",
      pricePerM2Min: 7000,
      pricePerM2Max: 10000,
      medianRent: 3200,
      airbnbRate: 30,
      grossYield: 4.3,
      annualAppreciation: 2.8,
      vacancyRate: 6,
      investmentScore: 65,
      description: "Quartier résidentiel populaire et accessible",
    },
    {
      id: "casa-aindiab",
      name: "Ain Diab",
      city: "casa",
      type: "touristique",
      pricePerM2Min: 13000,
      pricePerM2Max: 19000,
      medianRent: 6000,
      airbnbRate: 70,
      grossYield: 5.5,
      annualAppreciation: 4.3,
      vacancyRate: 5,
      investmentScore: 80,
      description: "Zone touristique côtière avec forte demande",
    },
    {
      id: "casa-bernoussi",
      name: "Bernoussi",
      city: "casa",
      type: "residential",
      pricePerM2Min: 6000,
      pricePerM2Max: 8500,
      medianRent: 2800,
      airbnbRate: 20,
      grossYield: 4,
      annualAppreciation: 2.3,
      vacancyRate: 7,
      investmentScore: 60,
      description: "Zone périphérique en expansion",
    },
    {
      id: "casa-ainchock",
      name: "Ain Chock",
      city: "casa",
      type: "residential",
      pricePerM2Min: 5500,
      pricePerM2Max: 7500,
      medianRent: 2400,
      airbnbRate: 15,
      grossYield: 3.8,
      annualAppreciation: 2,
      vacancyRate: 8,
      investmentScore: 55,
      description: "Zone populaire avec potentiel de développement",
    },
  ],
};

export function getQuartiersByCity(city: City): QuartierData[] {
  return QUARTIERS[city] || [];
}

export function getQuartierById(id: string): QuartierData | undefined {
  for (const quartiers of Object.values(QUARTIERS)) {
    const found = quartiers.find((q) => q.id === id);
    if (found) return found;
  }
  return undefined;
}

export function getAverageMetrics(city: City) {
  const quartiers = getQuartiersByCity(city);
  if (quartiers.length === 0) return null;

  return {
    avgPricePerM2:
      quartiers.reduce(
        (sum, q) => sum + (q.pricePerM2Min + q.pricePerM2Max) / 2,
        0,
      ) / quartiers.length,
    avgRent:
      quartiers.reduce((sum, q) => sum + q.medianRent, 0) / quartiers.length,
    avgYield:
      quartiers.reduce((sum, q) => sum + q.grossYield, 0) / quartiers.length,
    avgAppreciation:
      quartiers.reduce((sum, q) => sum + q.annualAppreciation, 0) /
      quartiers.length,
  };
}

